// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace VirgoGameplayTags
{
	/* Input Tags */
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Equip);
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Unequip);
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack);

	/* Shared Tags */
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Dead);

	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);

	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_RangedHit);
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_SpawnBullet);
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitPause);
	
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);

	/* Player Tags */
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip);
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip);
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Sword);
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_FireBall);

	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Sword);
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_AuraStaff);

	/* Enemy Tags */
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_MeleeAttack);
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_RangedAttack);

	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon_Sword);
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon_ShamanStaff);
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon_Slingshot);
	GASTEMPLATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon_Spear);


}